### Index method
GET http://localhost:3000/api/jokes

### Test successfully posts a joke
POST http://localhost:3000/api/jokes
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2NTUxNzAyODEsInN1YiI6MX0.vjTp15CZt6SP2xGBN6nfDLPt2IQarGsipsXIVt-8imE

{
    "category_id": 1,
    "body": "The furniture store keeps calling me to come back, but all I wanted was one night stand"
}

### Test unsuccessfully posts a joke
POST http://localhost:3000/api/jokes
Content-Type: application/json

{
    "body": "The furniture store keeps calling me to come back, but all I wanted was one night stand"
}

### Show joke id: 1
GET http://localhost:3000/api/jokes/1

### Unsuccessfully show joke id: 1000
GET http://localhost:3000/api/jokes/1000


### successfully update joke 1
PUT http://localhost:3000/api/jokes/1
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2NTUxNzAyODEsInN1YiI6MX0.vjTp15CZt6SP2xGBN6nfDLPt2IQarGsipsXIVt-8imE
{
    "body": "A programming joke",
    "category_id": 2
}

### Delete joke with id 1
DELETE http://localhost:3000/api/jokes/1

### Unsuccessfully delete joke with id 1000
DELETE http://localhost:3000/api/jokes/1000

### get random joke that is a pun
GET http://localhost:3000/api/jokes/random?category=puns

### get random joke that is a programming joke
GET http://localhost:3000/api/jokes/random?category=programming

### unsuccessfully get random joke from a category that doesnt exist
GET http://localhost:3000/api/jokes/random?category=funnyones


### create user
POST http://localhost:3000/api/auth/sign_up
Content-Type: application/json

{
    "username": "Simon6",
    "email": "simon6@test.com",
    "password": "password2",
    "password_confirmation": "password2"
}


### sign_in with correct details
POST http://localhost:3000/api/auth/sign_in
Content-Type: application/json

{
    "email": "simon3@test.com",
    "password": "password2"
}

### unsuccessful sign in with incorrect details
POST http://localhost:3000/api/auth/sign_in
Content-Type: application/json

{
    "email": "simon3@test.com",
    "password": "password3"
}

### Get categories
GET http://localhost:3000/api/categories